//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db_transporte_sanitario
{
    using System;
    using System.Collections.Generic;
    
    public partial class ambulancia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ambulancia()
        {
            this.equipe = new HashSet<equipe>();
            this.solicitacoes_ambulancias = new HashSet<solicitacoes_ambulancias>();
        }
    
        public int idAmbulancia { get; set; }
        public string NomeAmbulancia { get; set; }
        public string StatusAmbulancia { get; set; }
        public string TipoAM { get; set; }
        public Nullable<int> Desativado { get; set; }
        public Nullable<int> Bica { get; set; }
        public Nullable<System.DateTime> BicaDtHr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipe> equipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<solicitacoes_ambulancias> solicitacoes_ambulancias { get; set; }
    }
}
