//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db_transporte_sanitario
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DAHUEEntities : DbContext
    {
        public DAHUEEntities()
            : base("name=DAHUEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ambulancia> ambulancia { get; set; }
        public virtual DbSet<bloqueio> bloqueio { get; set; }
        public virtual DbSet<cancelados_pacientes> cancelados_pacientes { get; set; }
        public virtual DbSet<desbloqueioam> desbloqueioam { get; set; }
        public virtual DbSet<enderecos> enderecos { get; set; }
        public virtual DbSet<equipe> equipe { get; set; }
        public virtual DbSet<equipe_solam> equipe_solam { get; set; }
        public virtual DbSet<historico> historico { get; set; }
        public virtual DbSet<prontuarios> prontuarios { get; set; }
        public virtual DbSet<prontuariosupas> prontuariosupas { get; set; }
        public virtual DbSet<referencias> referencias { get; set; }
        public virtual DbSet<solicitacoes_agendamentos> solicitacoes_agendamentos { get; set; }
        public virtual DbSet<solicitacoes_ambulancias> solicitacoes_ambulancias { get; set; }
        public virtual DbSet<solicitacoes_paciente> solicitacoes_paciente { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
