//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db_transporte_sanitario
{
    using System;
    using System.Collections.Generic;
    
    public partial class desbloqueioam
    {
        public int idDesbloqueioAM { get; set; }
        public string Registrado { get; set; }
        public string DthrDesblo { get; set; }
        public Nullable<int> fkAMd { get; set; }
    }
}
