//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db_transporte_sanitario
{
    using System;
    using System.Collections.Generic;
    
    public partial class enderecos
    {
        public int idControle { get; set; }
        public string NomeUnidade { get; set; }
        public string Endereco { get; set; }
        public string Telefone { get; set; }
        public string Distancia { get; set; }
        public string Minutos { get; set; }
    }
}
