//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db_transporte_sanitario
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipe_solam
    {
        public Nullable<int> idequipe { get; set; }
        public Nullable<int> idSolAM { get; set; }
        public int idEquipe_solamcol { get; set; }
    
        public virtual equipe equipe { get; set; }
    }
}
