//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db_transporte_sanitario
{
    using System;
    using System.Collections.Generic;
    
    public partial class historico
    {
        public int IdHistorico { get; set; }
        public string Usuario { get; set; }
        public System.DateTime DtHrRegistro { get; set; }
        public int idPaciente_Solicitacao { get; set; }
        public string Obs { get; set; }
    
        public virtual solicitacoes_paciente solicitacoes_paciente { get; set; }
    }
}
