//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db_transporte_sanitario
{
    using System;
    using System.Collections.Generic;
    
    public partial class prontuarios
    {
        public int idProntuarios { get; set; }
        public string NomePaciente { get; set; }
        public string NomedaMae { get; set; }
        public string NomeSoliciante { get; set; }
        public string RgPaciente { get; set; }
        public string RgSolicitante { get; set; }
        public string DtNascimento { get; set; }
        public string DtAtendimento { get; set; }
        public string Telefone { get; set; }
        public string Unidade { get; set; }
        public string Internacao { get; set; }
        public string Dias { get; set; }
        public string Obs { get; set; }
        public string DtSolicitacao { get; set; }
        public string Status { get; set; }
        public string Funcionario { get; set; }
        public string DtRetirada { get; set; }
        public string Motivo_Rg { get; set; }
        public string DtHrFato { get; set; }
        public string LocalFato { get; set; }
    }
}
