//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db_transporte_sanitario
{
    using System;
    using System.Collections.Generic;
    
    public partial class referencias
    {
        public int referencias_id { get; set; }
        public string ALTA_HOSPITALAR { get; set; }
        public string AVALIACAO_DE_MEDICO_ESPECIALISTA { get; set; }
        public string AVALIACAO_DE_PROFISSIONAL_NAO_MEDICO { get; set; }
        public string CONSULTA_AGENDADA { get; set; }
        public string DEMANDA_JUDICIAL { get; set; }
        public string EVENTO_COMEMORATIVO_DO_MUNICIPIO { get; set; }
        public string EVENTO_DE_CULTURA_LAZER_OU_RELIGIAO { get; set; }
        public string EVENTO_ESPORTIVO { get; set; }
        public string EXAME_AGENDADO { get; set; }
        public string EXAME_DE_URGENCIA { get; set; }
        public string INTERNACAO_EM_ENFERMARIA { get; set; }
        public string INTERNACAO_EM_UTI { get; set; }
        public string PROCEDIMENTO { get; set; }
        public string RETORNO { get; set; }
        public string SALA_VERMELHA_EMERGENCIA { get; set; }
        public string TRANSPORTE_DE_INSUMOS_PRODUTOS_MATERIAIS { get; set; }
        public string TRANSPORTE_DE_PROFISSIONAIS { get; set; }
        public string TRANSFERENCIA { get; set; }
    }
}
